cmake_minimum_required(VERSION 3.16)
project(labs_fr3_kinematics)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(moveit_core REQUIRED)
find_package(moveit_ros_planning REQUIRED)
add_executable(labs_fr3_ik src/labs_fr3_ik.cpp)
ament_target_dependencies(labs_fr3_ik rclcpp moveit_core moveit_ros_planning)
install(TARGETS labs_fr3_ik DESTINATION lib/${PROJECT_NAME})
ament_package()
